### ISSUE TITLE
🎄 Final version of product table page for HTML

### ISSUE THREAD

**Issue by John-zaviago** [zaviagodev/Zaviago-Portal-HTML#7]
Finalizing the new table for all table and all pages.

**Note that this will be final major changes to the design and codes.**

This task does not include API integration.

**Checklist:** 

- [x] Figma design
- [x] Figma prototype
- [x] Html Design by @Asadyaseen

please check prototype here:
https://www.figma.com/proto/ng90eGRzbM7zYJF9x3GLXF/Product-table-page?node-id=22%3A16609&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2%3A5263

Link for design here: 
https://www.figma.com/file/ng90eGRzbM7zYJF9x3GLXF/Product-table-page?node-id=82%3A6621&t=A2be6ww9PK4U893X-1

Design Approved by John:

**Comment by John-zaviago** [comment]
Need @Asadyaseen123 to start working on this today

**Comment by John-zaviago** [comment]
Before half day pushing the code to git

**Comment by John-zaviago** [comment]
I will review it today

**Comment by Asadyaseen123** [comment]
Okay

**Comment by kornpongsakorn** [comment]
Review first round have 6 point to fix.
Link: https://www.figma.com/file/ng90eGRzbM7zYJF9x3GLXF/Product-table-page?node-id=325%3A10678&t=Ye6SQbKgb3nrB4JU-1

and
https://www.figma.com/proto/ng90eGRzbM7zYJF9x3GLXF/Product-table-page?page-id=325%3A9937&node-id=325%3A10678&viewport=2159%2C-123%2C0.29&scaling=scale-down-width&starting-point-node-id=325%3A10104



![Image](https://user-images.githubusercontent.com/120356124/208610040-2ca5c7fd-6da2-446b-b0e5-3b0e27f432d4.png)

**Comment by Asadyaseen123** [comment]
I'm working on it

**Comment by Asadyaseen123** [comment]
Push the on github

**Comment by kornpongsakorn** [comment]
Roger that.

**Comment by kornpongsakorn** [comment]
approve.
